### PR TITLE
Revert "bacon : Update adreno blobs to hammerhead MRA58K"

### PR DESCRIPTION
**Pull request by Herna1994**
This reverts commit 32b933942ea381d79d5555b2baf69e7072df4d1f.

### CODE REVIEW

**Comment by Thecrazyskull** [comment]
Any reason for this? Those new adreno blobs are neccesary to boot.

**Comment by Herna1994** [comment]
They are not neccesary. Old ones should boot too.

Using Nexus 5 files is not really recommended, since differences between full CAF and AOSP are some kind of big.

**Comment by Thecrazyskull** [comment]
It required new blobs on my titan (8226) to boot but dunno if its the same case on bacon since i dont own it, was just curious :)

**Comment by Herna1994** [comment]
Well, as I said to h2064, is better to give a try with permissive selinux and stock blobs, and in case it does not boot to update some of the files. But actually the Nexus 5 files are not working.

**Comment by Herna1994** [comment]
I´ve tried both combinations and none of them worked.

**Comment by h2o64** [comment]
Problem is kernel side. I'll fix soonish

**Pull request closed without merging**
